import argparse
import json
from pathlib import Path
import matplotlib.pyplot as plt


def latex_escape(s: str) -> str:
    repl = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(repl.get(ch, ch) for ch in s)


def fmt_num(x, sig=3):
    if x is None:
        return ""
    try:
        s = f"{x:.{sig}g}"
        return s
    except Exception:
        return str(x)


def to_num(v):
    if v is None:
        return None
    if isinstance(v, (int, float)):
        return float(v)
    if isinstance(v, dict):
        for val in v.values():
            n = to_num(val)
            if n is not None:
                return n
    if isinstance(v, (list, tuple)):
        for val in v:
            n = to_num(val)
            if n is not None:
                return n
    return None


def load_run(path, label):
    with open(path, "r") as f:
        data = json.load(f)

    pts_raw = [d for d in data if d.get("metric_value") != "original"]
    orig = next((d for d in data if d.get("metric_value") == "original"), None)

    rows = []
    for p in pts_raw:
        fr = to_num(p.get("flops_ratio"))
        pr = to_num(p.get("params_ratio"))
        ppl = to_num(p.get("ppl"))
        if fr is None or pr is None or ppl is None:
            continue
        rows.append(
            {
                "label": label,
                "metric_value": p.get("metric_value"),
                "flops_ratio": fr,
                "params_ratio": pr,
                "ppl": ppl,
                "note": "",
                "eval_results": p.get("eval_results"),
            }
        )

    if orig is not None:
        ppl_orig = to_num(orig.get("ppl"))
        if ppl_orig is not None:
            rows.append(
                {
                    "label": label,
                    "metric_value": orig.get("metric_value", "original"),
                    "flops_ratio": 1.0,
                    "params_ratio": 1.0,
                    "ppl": ppl_orig,
                    "note": "(orig)",
                    "eval_results": orig.get("eval_results"),
                }
            )

    rows.sort(key=lambda x: x["flops_ratio"])

    return {
        "label": label,
        "flops_x": [r["flops_ratio"] for r in rows],
        "params_x": [r["params_ratio"] for r in rows],
        "ppl_y": [r["ppl"] for r in rows],
        "rows": rows,
    }


def make_latex_table(series, out_dir: Path, name: str, title: str):
    table_name = (
        f"compressibility_table_{name}.tex" if name else "compressibility_table.tex"
    )
    tex_path = out_dir / table_name

    lines = []
    lines.append("% Auto-generated by compressibility plotting script\n")
    lines.append("\\begin{table}[t]\n")
    lines.append("\\centering\n")
    lines.append("\\small\n")
    lines.append("\\begin{tabular}{lccccc}\n")
    lines.append("\\toprule\n")
    lines.append(
        "Run & Compression & FLOPs ratio & Params ratio & Perplexity & PPL / orig\\\\\n"
    )
    lines.append("\\midrule\n")
    for s in series:
        orig_row = None
        for r in s["rows"]:
            if r.get("note") == "(orig)" or str(r.get("metric_value")) == "original":
                orig_row = r
                break
        orig_ppl = orig_row["ppl"] if orig_row is not None else None
        first = True
        for r in s["rows"]:
            run_label = latex_escape(r["label"]) if first else ""
            first = False
            comp = r.get("metric_value")
            if str(comp) == "original":
                comp_str = "1.0 (orig)"
            elif isinstance(comp, (int, float)):
                comp_str = fmt_num(comp)
            elif comp is None:
                comp_str = ""
            else:
                comp_str = latex_escape(str(comp))
            rel_ppl_str = ""
            if orig_ppl is not None and r["ppl"] is not None and orig_ppl != 0:
                rel_ppl = r["ppl"] / orig_ppl
                rel_ppl_str = fmt_num(rel_ppl)
            lines.append(
                f"{run_label} & {comp_str} & {fmt_num(r['flops_ratio'])} & {fmt_num(r['params_ratio'])} & {fmt_num(r['ppl'])} & {rel_ppl_str}\\\\\n"
            )
        lines.append("\\addlinespace\n")
    lines.append("\\bottomrule\n")
    lines.append("\\end{tabular}\n")
    lines.append(
        f"\\caption{{{latex_escape(title)}: perplexity and compression ratios across FLOPs/Params settings.}}\n"
    )
    label_key = (name or "compressibility").replace(" ", "-")
    lines.append(f"\\label{{tab:{latex_escape(label_key)}}}\n")
    lines.append("\\end{table}\n")

    tex_path.write_text("".join(lines), encoding="utf-8")
    return tex_path


def _comp_sort_key(label: str):
    if not label:
        return (1e9, label)
    token = label.split()[0]
    try:
        v = float(token)
        return (v, label)
    except Exception:
        return (1e9, label)


def make_latex_task_table(series, out_dir: Path, name: str, title: str):
    table_name = (
        f"compressibility_tasks_{name}.tex" if name else "compressibility_tasks.tex"
    )
    tex_path = out_dir / table_name

    compression_map = {}
    tasks = set()

    for s in series:
        for r in s["rows"]:
            eval_results = r.get("eval_results")
            if not eval_results:
                continue
            comp_val = r.get("metric_value")
            if str(comp_val) == "original":
                comp_label = "1.0 (orig)"
            elif isinstance(comp_val, (int, float)):
                comp_label = fmt_num(comp_val)
            elif comp_val is None:
                comp_label = ""
            else:
                comp_label = str(comp_val)
            if comp_label not in compression_map:
                compression_map[comp_label] = {}
            run_results = compression_map[comp_label].setdefault(r["label"], {})
            if isinstance(eval_results, dict) and "results" in eval_results:
                task_dict = eval_results["results"]
            else:
                task_dict = eval_results
            for task, metrics in task_dict.items():
                val = None
                if isinstance(metrics, (int, float)):
                    val = float(metrics)
                elif isinstance(metrics, dict):
                    for key in ["acc,none", "accuracy", "acc"]:
                        if key in metrics and isinstance(metrics[key], (int, float)):
                            val = float(metrics[key])
                            break
                    if val is None:
                        val = to_num(metrics)
                else:
                    val = to_num(metrics)
                if val is None:
                    continue
                run_results[task] = val
                tasks.add(task)

    task_order = sorted(tasks)
    run_order = [s["label"] for s in series]
    comp_labels = sorted(compression_map.keys(), key=_comp_sort_key)

    lines = []
    lines.append("% Auto-generated by compressibility plotting script (tasks table)\n")
    lines.append("\\begin{table}[t]\n")
    lines.append("\\centering\n")
    lines.append("\\small\n")
    col_spec = "ll" + "c" * len(task_order)
    lines.append(f"\\begin{{tabular}}{{{col_spec}}}\n")
    lines.append("\\toprule\n")
    header = ["Compression", "Run"] + [latex_escape(t) for t in task_order]
    lines.append(" & ".join(header) + "\\\\\n")
    lines.append("\\midrule\n")

    for comp_label in comp_labels:
        runs_dict = compression_map[comp_label]
        first = True
        for run_label in run_order:
            if run_label not in runs_dict:
                continue
            metrics = runs_dict[run_label]
            comp_cell = latex_escape(comp_label) if first else ""
            first = False
            row = [comp_cell, latex_escape(run_label)]
            for task in task_order:
                v = metrics.get(task)
                row.append(fmt_num(v) if v is not None else "")
            lines.append(" & ".join(row) + "\\\\\n")
        lines.append("\\addlinespace\n")

    lines.append("\\bottomrule\n")
    lines.append("\\end{tabular}\n")
    lines.append(
        f"\\caption{{Task-level evaluation for {latex_escape(title)} across compression ratios. Each compression group has one row per run (e.g., pretrained vs regularized).}}\n"
    )
    label_key = (name or "compressibility_tasks").replace(" ", "-")
    lines.append(f"\\label{{tab:{latex_escape(label_key)}}}\n")
    lines.append("\\end{table}\n")

    tex_path.write_text("".join(lines), encoding="utf-8")
    return tex_path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--runs", nargs="+", required=True, help="format: /path/to/results.json:Label"
    )
    ap.add_argument("--out_dir", default=".")
    ap.add_argument("--title", default="ViT compressibility", help="Plot title prefix")
    ap.add_argument("--name", help="Plot name")
    args = ap.parse_args()

    series = []
    for r in args.runs:
        if ":" in r:
            p, lbl = r.split(":", 1)
        else:
            p, lbl = r, Path(r).parent.name
        series.append(load_run(p, lbl))

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    name_suffix = f"_{args.name}" if args.name else ""

    plt.figure()
    for s in series:
        if not s["flops_x"] or not s["ppl_y"]:
            continue
        plt.plot(s["flops_x"], s["ppl_y"], marker="o", label=s["label"])
    plt.xscale("linear")
    plt.yscale("log")
    plt.xlabel("FLOPs ratio")
    plt.ylabel("Perplexity (log scale)")
    plt.title(f"{args.title} vs FLOPs")
    plt.legend()
    plt.grid(True, linestyle="--", alpha=0.3)
    plt.tight_layout()
    flops_path = out_dir / f"compressibility_flops{name_suffix}.pdf"
    plt.savefig(flops_path, dpi=200)

    plt.figure()
    for s in series:
        if not s["params_x"] or not s["ppl_y"]:
            continue
        plt.plot(s["params_x"], s["ppl_y"], marker="o", label=s["label"])
    plt.xscale("linear")
    plt.yscale("log")
    plt.xlabel("Parameters ratio")
    plt.ylabel("Perplexity (log scale)")
    plt.title(f"{args.title} vs Parameters")
    plt.legend()
    plt.grid(True, linestyle="--", alpha=0.3)
    plt.tight_layout()
    params_path = out_dir / f"compressibility_params{name_suffix}.pdf"
    plt.savefig(params_path, dpi=200)

    tex_path = make_latex_table(series, out_dir, args.name, args.title)
    print(f"Wrote LaTeX table to: {tex_path}")
    tasks_tex_path = make_latex_task_table(series, out_dir, args.name, args.title)
    print(f"Wrote tasks LaTeX table to: {tasks_tex_path}")


if __name__ == "__main__":
    main()
